### ISSUE TITLE
getSelectedRowNames, getSelectedColnames, selectRows, selectCols?

### ISSUE THREAD

**Issue by paul-shannon** [MaayanLab/clustergrammer#7] opened 2017-08-03 19:26 UTC
Hi Nick,

We are making pretty good progress on the RClustergrammer package.  It's a pleasure working with what you have created.

Here are a few requests, all regarding selections: either retrieving the currently selected rows or column names for use in R, or making Clustergrammer selections from R - the programmatic equivalent, say, of clicking on a subcluster, after which the other rows (or columns) are grayed out.

 All we need in either case is the equivalent functions in your javascript API.  Maybe they already exist?

To sketch out some pseudo-code:

  cg = Clustergrammer(args);
  var nodeNames = cg.getSelectedRowNames()
  var colNames = cg.getSelectedColumnNames()
  cg.selectRows(["A", "B", "C"])
  cg.selectColumns(["X", "Y", "Z"])

Possible?

**Comment by cornhundred** [comment] 2017-08-03 20:11
Hi Paul, 

That's great, I'm glad progress is being made. If I understand you correctly you want to be able to get the current rows/columns and set the current rows/columns. 

The Clustergrammer.js API ([API docs](http://clustergrammer.readthedocs.io/clustergrammer_js.html#clustergrammer-js-api)) supports setting the current rows/columns and you can get the current rows/col from the `cgm` object (I'll build an API for getting rows/columns later). 

You can get the current row/column names using 

```
// get current row names
cgm.params.network_data.row_nodes_names

// get current column names
cgm.params.network_data.col_nodes_names
```

You can set the current rows/columns using 
```
cgm.filter_viz_using_names({'row':['LRRK2','NRK'], 'col':['H2106', 'H23']})
```
You can leave the `row` and/or `col` attributes empty to reset the rows/columns. 

You can try running these commands in the developer console of the github.io page: http://maayanlab.github.io/clustergrammer/ 

Let us know if that is what you are looking for. 

Best,
Nick

**Comment by paul-shannon** [comment] 2017-08-04 16:31
Thanks, Nick.   I gave this a try, and it works as you say.

However, I hope to:

— scenario 1
   a) select a row or cluster of rows interactively in clustergrammer
   b) in javascript, retrieve the names of just those selected rows 

— scenario 2
  a) in javascript, select rows by name, programmatically

I hope to do both of these operations this with columns as well.

Possible?

Thanks!

 - Paul

**Comment by cornhundred** [comment] 2017-08-04 16:47
Hi Paul, 

Scenario 1
You can interactively select a row  or cluster of rows in two ways. You can [crop](http://clustergrammer.readthedocs.io/interacting_with_viz.html#cropping), where you draw out a region of interest that filters out only that area (then you can use the previous command to get the row/col names in JavaScript). You can also use the [interactive dendrogram](http://clustergrammer.readthedocs.io/interacting_with_viz.html#interactive-dendrogram) to crop into clusters of different sizes and to get the row/col names of the selected cluster. 

Scenario 2
Would the `cgm.filter_viz_using_names` endpoint work for this? You can use it to programmatically filter the visualization for rows/columns of interest. 

Let me know if that helps.

Best,
Nick

**Comment by paul-shannon** [comment] 2017-08-04 20:36
Hi Nick,

This all works great.   Thank you!

 - Paul

**Comment by cornhundred** [comment] 2017-08-05 15:06
Great, I'll close the issue then.

**Closed by cornhundred** 2017-08-05 15:06 UTC

**Comment by AmirAlavi** [comment] 2019-03-27 02:17
@cornhundred, I want to report which subset of rows the user has clicked on when they crop the matrix. To do so, I've used `matrix_update_callback` when constructing the Clustergrammer object. However, the callback doesn't seem to be passed any arguments. So then I called `cgm.params.network_data.row_nodes_names` from inside the callback as you suggest above. However, the issue is that this list of row_nodes is outdated; it's what the matrix had before the user cropped. I want the new subset of nodes that is the result of the current filtering. How can I get that, as soon as it happens?
```javascript
/* This is the function I pass as 'matrix_update_callback' */
handleMatrixUpdate(matrix_filter) {
    /* when I set a breakpoint here, 'matrix_filter' is null,
    so this callback isn't passed any info */
    const new_rows = this.cgm.params.network_data.row_nodes_names; /* But this doesn't give
    me what I want, `new_rows` is outdated, it's what was visible before the current matrix update */
}
```

**Comment by AmirAlavi** [comment] 2019-03-27 02:28
After looking at the [code](https://github.com/MaayanLab/clustergrammer/blob/master/src/update/update_viz_with_network.js) that calls the callback, it looks like in order to get the behavior I am looking for, one of these two must be the case:
1. We need a new optional callback, something like `matrix_updated_callback`, to be called after the update completes
2. We need to call the callback function and pass in `new_network_data`
Either one would require a fork and rebuild of Clustergrammer. However, I'm hoping there's some other way to do this that I'm not aware of.
Thanks!
